CREATE TABLE IF NOT EXISTS accounts(
  id VARCHAR(255) NOT NULL primary key COMMENT 'primary key',
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT 'Time Created',
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Last Update',
  name varchar(255) COMMENT 'User Name',
  email varchar(255) COMMENT 'User Email',
  picture varchar(255) COMMENT 'User Picture'
) default charset utf8 COMMENT '';

CREATE TABLE IF NOT EXISTS posts(
  id INT NOT NULL AUTO_INCREMENT  PRIMARY KEY COMMENT 'Primary Key',
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT 'Time Created',
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Last Update',
  body VARCHAR (255),
  imgUrl VARCHAR (255) COMMENT NOT NULL'Post Image',
  likes INT COMMENT 'post likes',
  creatorId VARCHAR(255) NOT NULL COMMENT 'FK: User Account',

  FOREIGN KEY (creatorId) REFERENCES accounts(id) ON DELETE CASCADE
)

CREATE TABLE IF NOT EXISTS likes(
  id INT AUTO_INCREMENT  PRIMARY KEY 'Primary Key',
  creatorId VARCHAR(255) NOT NULL COMMENT 'FK: User Account',
  postId INT NOT NULL COMMENT 'FK: Post ID'
)